### ISSUE TITLE
[BUG] Oracle Columns with DataType of Number Precision/Scale Fail and Incorrect DataType Lookup Query with connector athena-oracle

### ISSUE THREAD

**Issue by gss2002** [awslabs/aws-athena-query-federation#2418]
**Description**
Oracle allows for DataType of NUMBER to be utilized within a Oracle Table. The details on Oracle NUMBER DataType are provided [here](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#SQLRF-GUID-9401BC04-81C4-4CD5-99E7-C5E25C83F608). I've attached screenshots showing data before and after my proposed fix. Also discovered during the debug of this problem it was determined that the Query Used to get Information on table record types is incorrect. There was an assumption made that all requests to an Oracle DB would be with the DB owning user this is a poor assumption in an enterprise environment.

[USER_TAB_COLS vs ALL_TAB_COLS](https://docs.oracle.com/en/database/oracle/oracle-database/21/refrn/ALL_TAB_COLS.html)
`
4.106 ALL_TAB_COLS
ALL_TAB_COLS describes the columns of the tables, views, and clusters accessible to the current user.

To gather statistics for this view, use the DBMS_STATS package.

This view differs from ALL_TAB_COLUMNS in that system-generated hidden columns are not filtered out.

Related Views

DBA_TAB_COLS describes the columns of all tables, views, and clusters in the database.

USER_TAB_COLS describes the columns of the tables, views, and clusters owned by the current user. This view does not display the OWNER column.
`

**To Reproduce**
1) Create Oracle Table with at least 1 record DataType of NUMBER with and without precision/scale and insert records with values such as 42.24, 1000.99, etc into that column.
2) Execute A Query against the table and the values will become truncated.

**Expected behavior**
Oracle Number types should return Decimal Data Types 

**Screenshots / Exceptions / Errors**

Incorrect Output showing Oracle DataType NUMBER Column Definitions that have Precision/Scale are being truncated:
<img width="383" alt="oracle_connector_nofix_decimal_types" src="https://github.com/user-attachments/assets/a3121b4b-3b92-4bd5-84a3-ed678bc51a0b">

Incorrect Output showing Oracle DataType NUMBER data output showing records being truncated:
<img width="1341" alt="oracle_connector_nofix_data_output_bigint_types" src="https://github.com/user-attachments/assets/1efdc962-74b7-4237-ac80-53857e10e451">

Correct Output showing Oracle DataType NUMBER Column Definitions that have Precision/Scale with proposed fix:
<img width="1342" alt="oracle_connector_wfix_data_output_decimal_types" src="https://github.com/user-attachments/assets/a6f2b3d7-177e-409b-ae18-9284d59071e7">

Correct Output showing Oracle DataType NUMBER data output showing records correctly with Precision/Scale Proposed Fix:
<img width="370" alt="oracle_connector_wfix_decimal_types" src="https://github.com/user-attachments/assets/b757f8cf-72a5-4bc6-bedb-04568169b684">

**Connector Details (please complete the following information):**
 - Version: 2024.46.1
 - Name athena-oracle / jdbc
 - Athena Query IDs n/a

**Additional context**
This problem is very similar to the problem that was fixed with Postgres Connector but Postgres Connector Handlers are implemented much differently: https://github.com/awslabs/aws-athena-query-federation/pull/957

**Comment by AbdulR3hman** [comment]
this is addressed in https://github.com/awslabs/aws-athena-query-federation/pull/2453

**Comment by gss2002** [comment]
@AbdulR3hman thank you for the fix but  this fix is NOT complete you didn't fix the query being used to look up partitions. For this to work with a user who is not the table owner say a user with read only access to a table which is a legit use case. In enterprise env's we are NOT allowed to use table owner users to read data. Please fix! 

https://github.com/awslabs/aws-athena-query-federation/blob/3d60833d805473a87240365b0d526f4971b4f442/athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java#L94

https://github.com/awslabs/aws-athena-query-federation/blob/3d60833d805473a87240365b0d526f4971b4f442/athena-oracle/src/main/java/com/amazonaws/athena/connectors/oracle/OracleMetadataHandler.java#L165
