### ISSUE TITLE
[BUG] Incompatible mapping for postgres numeric columns with connector Athena.JDBC

### ISSUE THREAD

**Issue by emerson-h** [awslabs/aws-athena-query-federation#360]
**Describe the bug**

The JDBC type mappings for Postgres numeric types to Decimal types produce non-functional column mappings when the Postgres column has the type `numeric` without a precision and scale specified.   

**To Reproduce**
1. Create a postgres instance with a numeric column 
```sql
create table if not exists test_data
(
	id serial not null
		constraint test_data_pkey
			primary key,
	bad_number numeric,
	valid_number numeric(12,4)
);
```
2. Create a mapping for the table using the JDBC connector 
4. In the Athena table catalog, the bad_number column will be mapped as `decimal(131089,0)`
5. Executing a query will result in `INVALID_FUNCTION_ARGUMENT: DECIMAL precision must be in range [1, 38]`

**Expected behavior**
A loss of precision in the mapping by down converting into an Athena compatible decimal would be preferable to not being able to query.  

**Screenshots / Exceptions / Errors**
![image](https://user-images.githubusercontent.com/974877/108766571-524cc480-7523-11eb-8d1b-7fcb0462ac20.png)

**Connector Details (please complete the following information):**
 - Version: 2020.51.1
 - Name jdbc
 - Athena Query IDs: 2407d0d5-940f-49f0-b643-451b648aeba2

**Comment by ciaranMcK-reward** [comment]
Has anyone managed to fix this or is there a workaround? I have exactly the same issue as described above. This is a major blocker!

**Comment by linahovanessian** [comment]
Is there any update for this? Any workaround?

**Comment by ciaranMcK-reward** [comment]
Hopefully, this is useful for someone. As a workaround, I created a view at the database level which did not select the numeric field (Luckily I could do this as the numeric field was not needed). I then updated my query to reference this new view instead of the table. This means the jdbc connector will reference my new view and this error goes away. @linahovanessian @rajkum-paf @emerson-h

**Comment by linahovanessian** [comment]
Thanks @ciaranMcK-reward . Well unfortunately I need those numeric fields exactly ! As a workaround , I found out that if we define length/precision (less than 38) for numeric columns , everything will work perfectly. But it will be really nice to fix this in the connector itself.

**Comment by marghidanu** [comment]
Just bumped into this problem yesterday; any news on this? I see there was a PR in place.

**Comment by akuzin1** [comment]
Fix has been merged in and released with version 2023.2.1. The new behavior will set precision and scale to default values if encounters `Numeric` type with unspecified parameters.

**Comment by chethanuk** [comment]
Still getting error `INVALID_FUNCTION_ARGUMENT: DECIMAL precision must be in range [1, 38]` in AthenaPostgreSQLConnector — version 2023.18.1

**Comment by emerson-h** [comment]
My organization still encounters this issue as well.  It is not resolved.

**Comment by akuzin1** [comment]
Reopening issue, will add item for investigation. Thank you @chethanuk for quick fix.

**Comment by grrolland** [comment]
Hello,

I think I may have found the source of the bug: 

The method for resolving the type is as follows: https://github.com/awslabs/aws-athena-query-federation/blob/454ad41e1e066619798732ee347712c7c0ea73d3/athena-postgresql/src/main/java/com/amazonaws/athena/connectors/postgresql/PostGreSqlMetadataHandler.java#L376

This one is called by this method: 
https://github.com/awslabs/aws-athena-query-federation/blob/4bd3f11197e5fd3ed320970addcffb15ce224ab5/athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java#L257

In this last method, the metadata are requested from the database. 
For a "numeric" type, when querying column metadata, postgresql returns the column's maximum precision: (see https://stackoverflow.com/questions/60131568/databasemetadata-getcolumns-has-strange-column-size-for-int-value)

So for a numeric type, Postgresql answers "131089" (the correct value is "131072", see https://www.postgresql.org/docs/14/datatype-numeric.html).

**Comment by grrolland** [comment]
Hello,

My apologies, I took the wrong version of the connector to test and report this incident. After analyzing our system, it turns out that we were using a largely obsolete version. 

After updating our system, the parameter-free numeric conversion works. The initial correction from @akuzin1 works well.

I therefore deleted my PR and the associated branch.

Sorry again for the misunderstanding.

Regards,
